class Organization < ActiveRecord::Base

  def verification_tasks
    VerificationTask.where("mapped_organization_id = #{id} OR mapped_institute_id = #{id}")
  end
# DONE "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Ability to work independently",

# DONE "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Commitment",

# FUCK OFF "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Attitude",

# FUCK OFF "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Commitment to a goal",

# DONE "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Decision making",

# DONE "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Team-work",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Respect and Humility",

# "Rate the candidate on a scale of 1 to 5 on: Team Work (1 being the lowest and 5 being the highest)",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Leadership",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Capability to work independently",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Working under pressure",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Discipline",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Initiative on tasks",

# "Rate the candidate on a scale of 1 to 5 on: Respect and Humility (1 being the lowest and 5 being the highest)",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Integrity",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Respect and humility",

# "How would you rate your overall experience with IDfy on a scale of 1 to 5? (1:lowest, 5:highest)",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Organisation and Planning",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Professionalism",

# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Decision making and initiative",

# "Rate the candidate on a scale of 1 to 5 on: Integrity (1 being the lowest and 5 being the highest)",
  def cap_to_work_indep
    a = "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Capability to work independently"
    qids = Question.where(content: a).select(:id)
    profile_ids = verification_tasks.select(:profile_id)
    res_ids = VerificationTask.where(block_type: "Reference", profile_id: profile_ids).select(:survey_response_id)
    answers = Answer.where(survey_response_id: res_ids, question_id: qids).pluck(:details)
    {
      "1" => answers.select{|s| s.include?('1')}.count,
      "2" => answers.select{|s| s.include?('2')}.count,
      "3" => answers.select{|s| s.include?('3')}.count,
      "4" => answers.select{|s| s.include?('4')}.count,
      "5" => answers.select{|s| s.include?('5')}.count,
    }
  end

  def candidate_commitment
    a = "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Commitment"
    qids = Question.where(content: a).select(:id)
    profile_ids = verification_tasks.select(:profile_id)
    res_ids = VerificationTask.where(block_type: "Reference", profile_id: profile_ids).select(:survey_response_id)
    answers = Answer.where(survey_response_id: res_ids, question_id: qids).pluck(:details)
    {
      "1" => answers.select{|s| s.include?('1')}.count,
      "2" => answers.select{|s| s.include?('2')}.count,
      "3" => answers.select{|s| s.include?('3')}.count,
      "4" => answers.select{|s| s.include?('4')}.count,
      "5" => answers.select{|s| s.include?('5')}.count,
    }
  end

  def candidate_decision_making
    a = "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Decision making"
    qids = Question.where(content: a).select(:id)
    profile_ids = verification_tasks.select(:profile_id)
    res_ids = VerificationTask.where(block_type: "Reference", profile_id: profile_ids).select(:survey_response_id)
    answers = Answer.where(survey_response_id: res_ids, question_id: qids).pluck(:details)
    {
      "1" => answers.select{|s| s.include?('1')}.count,
      "2" => answers.select{|s| s.include?('2')}.count,
      "3" => answers.select{|s| s.include?('3')}.count,
      "4" => answers.select{|s| s.include?('4')}.count,
      "5" => answers.select{|s| s.include?('5')}.count,
    }
  end

  def candidate_team_work
    a = "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Team-work"
    qids = Question.where(content: a).select(:id)
    profile_ids = verification_tasks.select(:profile_id)
    res_ids = VerificationTask.where(block_type: "Reference", profile_id: profile_ids).select(:survey_response_id)
    answers = Answer.where(survey_response_id: res_ids, question_id: qids).pluck(:details)
    {
      "1" => answers.select{|s| s.include?('1')}.count,
      "2" => answers.select{|s| s.include?('2')}.count,
      "3" => answers.select{|s| s.include?('3')}.count,
      "4" => answers.select{|s| s.include?('4')}.count,
      "5" => answers.select{|s| s.include?('5')}.count,
    }
  end

#  [nil, "Job Performance (1-10)",
# "Would you recommend us to your colleagues/friends/family? ",
# "how afraid are the following people of me?",
# "what is your faverate hobby ",
# "What according to you are my professional strenghts?",
# "Any Co-Founders added or exited post-that? (if so, pls add details in Comments)",
# "Management effectiveness",
# "first cell no",
# "what is that change you think i should have in me ?",
# "Date of Birth",
# "Did the tenant make unreasonable demands or complaints?",
# "What best describes Nikhil Dhok's personality at work?",
# "Who were you thinking of verifying?",
# "Is there anything in this persons performance history that would raise a question on their employability?",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Ability to work independently",
# "Initiative/Innovation:   Can you give me an example of when he has come up with a new idea to improve the way work is done? What was the outcome? ",
# "How do you rate the user experience in taking this survey",
# "Leadership/Developing Subordinates:  How would you describe his leadership style? Can you give me an example of where he has developed his people? ",
# "What can vineet jawa improve upon?",
# "Any additional comments?",
# "AM I  STUDIED IN PIMPRI CHINCHWAD POLYTECHNIC",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Commitment",
# "How likely are you to recommend working with Nikhil Dhok to another colleague?",
# "Would you rehire this candidate? Please share the reason why if you would not rehire this candidate",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Attitude",
# "How would you rate our service ",
# "What are the candidate's strengths?",
# "Agent Name:",
# "Select the choices that accurately represent Hatim Baheranwala",
# "What can Abhimanyu Sanghi improve upon?",
# "How likely are you to recommend working with Hatim Baheranwala to another colleague?",
# "Why did he leave this role?",
# "In what areas does this team member need to improve?",
# "Rate my research skills (5 is the higest)",
# "Rate the candidate on - Ability to work with others",
# "I demonstrate the following behavior:",
# "Written feedback: greatest strength and one area Sandeep Warrier can improve upon",
# "Were you ever given a hug by Kaushik when you were dropped home?",
# "Self Reliance: Does he need to be managed? ",
# "Could you please tell me about a conflict the candidate had with another employee & how did he/she resolve the same",
# "Rate the candidate on a Scale of 1-5 (5 being highest): Perseverance & Motivation",
# "q",
# "Written feedback: greatest strength and one area Gautam N can improve upon",
# "name",
# "what is your pet name?",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Commitment to a goal",
# "Permanent Address",
# "Question#1",
# "How likely are you to recommend working with mahendran swamy to another colleague?",
# "Employee Name",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Decision making",
# "Rate me as a team player (5 is the highest)",
# "А в какой стране осели бы вы?",
# "Leadership Quality",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Team-work",
# "How much capital (other than lost income) did the founders collectively invest before Blume's round? (in Rs Lacs)",
# "How does the candidate communicate with his/her seniors?",
# "If yes, what were your key take aways?",
# "Rate Sandeep Warrier's team handling capability (10 being highest)",
# "Would you like to provide a positive recommendation for me?",
# "Could you comment on my general character and behaviour?",
# "P. F. Superannuation details: Do you intend to join TECIL P F /Superannuation",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Respect and Humility",
# " Is there anything else that you would like to add regarding the candidate or his application for this role?",
# "How well do i play marbles with peoples eyes?(1=  Lowest , 10 = Highest)",
# "Permanent Place of Posting",
# "Sex",
# "Any personal problems interfering  with Profile's job performance OR Professional Weakness",
# "I hereby furnish below particulars of the members of my family who would be eligible to receive Widow/Children Pension in the event of my death",
# "Location",
# "Alternate People",
# "Written feedback: greatest strength and one area Hatim Baheranwala can improve upon",
# "Rate Viraj for Geekiness on a scale of 1-10(10 being the highest)",
# "Are you aware of any actual or potential conflicts that may arise if you were to accept this position at Vodafone. Examples of conflict of interest include but are not limited to: Accepting a position that reports (directly or indirectly) into a family member or a close friend; Accepting a position where a close friend or a family member is a direct or indirect report; Having a close relationship with government minister or official; being a director or a significant shareholder of a supplier or customer or having an outside business activity that detracts from your responsibilities to Vodafone. If yes, please give details.",
# "Office Address",
# "Serial No. in Policy or Endorsement",
# "Contact number at Present Address",
# "My best one liner",
# "Will Tanya finally settle in India?",
# "What best describes Abhimanyu Sanghi's personality at work?",
# "Contact Number:",
# "Present Address",
# "Could you comment on my ability to work in a team?",
# "Effectiveness in Meeting Goals and Objectives",
# "How long have you worked with Mayank Jain?",
# "What is your AIM ?",
# "Most common phrases",
# "How likely are you to recommend working with this team member to others with a similar need? (1 is lowest; 5 is highest)",
# "What can aakash arora improve upon?",
# "Enter following details(First row for self)",
# "Rate the candidate on a scale of 1 to 5 on: Team Work (1 being the lowest and 5 being the highest)",
# "Time Management",
# "Date of visit:",
# "What would the candidate do if some team members weren't doing their share of the work?",
# "What can Keshav Viswanath improve upon?",
# "Claim ID",
# "Problem management",
# "What best describes Ruchi Sood's personality at work?",
# "Reasons for quitting the job?",
# "Name of Company",
# "What can Max Cameron improve upon?",
# "Written feedback: greatest strength and one area Raghav Kumar can improve upon",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Leadership",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Capability to work independently",
# "What type of communication style does he have? ",
# "How would you describe this candidates absenteeism, punctuality  record ?",
# "How likely are you to recommend working with Raghav Kumar to another colleague?",
# "How did you come to know of our service/website?",
# "How likely are you to recommend working with Abhimanyu Sanghi to another colleague?",
# "Period of Employment: ",
# "First Question",
# "Would you re-employ? Why/ Why not?",
# "Could you comment on the candidate’s ability to adhere to schedules and deadlines?",
# "MM/YYYY of startup incorporation?",
# "Other comments",
# "What can Karin Teodorovicz improve upon?",
# "Residential Address",
# "Bank A/C Number",
# "Russia vs India.Is Tanya more Indian than Russian?",
# "Did you enjoy being a part of the workshop?",
# "Viraj believes eating \"Jootha\" food destroys the mind. You believe him?",
# "How much more weight will Tanya gain if she has to stay in India for 6 months more",
# "what is your relationship with the candidate?",
# "Возвращаться ли Тане домой сразу как закончится стажировка?",
# "what is mandatory to improve personaly ",
# "What are the candidate's weaknesses?",
# "what is your name?",
# "Email ID:",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Working under pressure",
# " Rate me as a team player (5 is the highest)",
# "Any other comment you would like to write",
# "Rate me on - Technical competence",
# "Trust Address",
# "Have i ever stolen your chaddi in the past",
# "Who does this number belong to?",
# "Are you happy with your experience working with this team member?",
# "Каким умением Тане нужно обзавестись?",
# "Are there similar platforms on the market? What were your reasons for choosing them?",
# "Would you like to provide a positive recommendation for me? ",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Discipline",
# "Duties and Responsibilities (Nature of Work)",
# "What best describes aakash arora's personality at work?",
# "Select the choices that accurately represent Irshad Shaikh",
# "Write a few comments on Sandeep Warrier's overall personality and professional attitude",
# "Чего не хватает Тане для полного счастья?",
# "Select the choices that accurately represent aakash arora",
# "What will it take for Kaushik to join the GYM?",
# "What best describes Hatim Baheranwala's personality at work?",
# "Did the tenant leave the premise in a good condition?",
# "hio r u",
# "City where currently located",
# "Contact number at Permanent Address",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Initiative on tasks",
# "Rate Tanya's ability to curse autowallas in hindi",
# "Any prior city/cities that the co. was located at, before moving to current location?",
# "In what areas could the candidate improve?",
# "Person met on the address:",
# "Endorsement No",
# "Complete Employment Address (Mention house number/ alternate address in case interaction happened with alternate people)",
# "What will you write for candidate's ability to work in a team?",
# "What can Ruchi Sood improve upon?",
# "Attributes: How would you describe his personality type? ",
# "ghdjdj",
# "If no, what do you think should be improved?",
# "Rate me on - Perseverance and motivation",
# "Any other comments?",
# "How is he/she in terms of Integrity, Reliability & Commitment?",
# "What was the candidate's reason for leaving the position?",
# "What job role do you see me performing best in?",
# "Do you have any proceedings pending currently against you that can result in a conviction? If yes, please give details of the offence(s).",
# "Is there any improvement you would suggest to the service we provide, to make it more useful for you?",
# "Name",
# "How did you find the service? ",
# "Name & Address of Family Doctor, including telephone no. if any",
# "Commitment",
# "Who are you?",
# "Written feedback: greatest strength and one area Abhimanyu Sanghi can improve upon",
# "Below are some of the commonly-used phrases Viraj uses. Pick your favorite or add your own..",
# "What were his main duties and responsibilities?",
# "Question#2",
# "What does this team member do well?",
# "Technical competence",
# "Team Player",
# "Rate me on - Ability to work with others",
# "Rate the candidate on a scale of 1 to 5 on: Respect and Humility (1 being the lowest and 5 being the highest)",
# "Rate the candidate on - Technical competence",
# "Would you like to be a part of our Advanced Workshops in the future?",
# "How likely are you to recommend working with vineet jawa to another colleague?",
# "Do you recommend this candidate for a job with Gaboli?",
# "Question#4",
# "Is there any additional information that you would like to share with us regarding the candidate?",
# "Rate the candidate on ability to work with others",
# "ldskafghl",
# "Name and Address of nearest Kith & Kin",
# "Conclusion & additional comments about the Candidate:",
# "Client Name:",
# "Office Name",
# "Strengths: Can you list any of his strengths?",
# "Would you like to provide a positive recommendation for the candidate? (Yes / No)",
# "I hereby nominate the person (s)/ cancel the nomination made by me previously and nominate the person (s) mentioned below to receive the amount standing to my credit in the Employees Provident Fund, in the event of my death",
# "Income Tax details: Assessed up-to Assessment Year(from dd/mm/yyyy to dd/mm/yyyy)",
# "Would you rehire this candidate?",
# "Question#5",
# "Income Tax details: Designation & address of existing I.T.D",
# "What best describes vineet jawa's personality at work?",
# "Rate me on - Verbal communication / Written",
# "Income Tax details: Permanent A/c No",
# "P. F. Superannuation details: Name of Trust/ R P F C & Address",
# "Did the tenant give enough notice before moving out?",
# "What are the areas in which the I need to improve?",
# "How good are his driving skills? (Do comment with Compliments and insults)",
# "Is there anything else you would like to share about Hatim?",
# "What job role do you see the candidate performing best in?",
# "Education Details",
# "How likely are you to recommend working with Karin Teodorovicz to another colleague?",
# "Integrity",
# "Would you like to provide a positive recommendation for the candidate?",
# "Would you like to provide a positive recommendation for candidate?",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Integrity",
# "How often does the candidate visit his/her family.",
# "As  this  role  is  located  in  a  remote  location  in  India,  how  do  you  feel  he  will  adjust  to  the environment of the role?",
# "Are you aware of any actual or potential conflicts that may arise if you were to accept this position at Vodafone. Examples of conflict of interest include but are not limited to: Accepting a position that reports (directly or indirectly) into a family member or a close friend; Accepting a position where a close friend or a family member is a direct or indirect report; Having a close relationship with government minister or official; being a director or a significant shareholder of a supplier or customer or having an outside business activity that detracts from your responsibilities to Vodafone. If yes, please give details..!!",
# "Предложения по поводу следующей страны для стажировки",
# "Details of Employees/ Members including family members proposed for Insurance:",
# "Any other feedback?",
# "At which address is this number registered?",
# "Have you had the privilege of hearing Viraj's fake American accent?",
# "where do u stay?",
# "Name of the candidate:",
# "Teamwork / Collaboration (peers, subordinates, superiors): How does he get along with peers, subordinates and superiors? Can you give me some examples? ",
# "What do you do?",
# "Account Number: (KN/...................../................)",
# "По-моему, самое время выбирать профессию!Какую профессию Таня могла бы освоить?",
# "Viraj Kulkarni asks a LOT of questions. How many does he ask on an average per day?",
# "Would you recommend this service to your friends, family and housing complex? If no, why Not?",
# "Why did you not go through with the process? ",
# "r uy there",
# "How well does Viraj play the Tabla? (10 being the highest)",
# "What is Kaushik's favorite one line?",
# "Rehire Eligibility",
# "Select the choices that accurately represent Abhimanyu Sanghi",
# "How do you know me?",
# "Technical Ability: How would you rate his technical / professional ability? Why? ",
# "Would you in future consider going through with the verification process? If not, why not?",
# "Rate the candidate on - Verbal communication / Written",
# "Was the report self-explanatory?",
# "How am i in comparison to mogambo?",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Respect and humility",
# "Thinking about your interaction with Gangadhar Atmakuri, he/she demonstrates the following behaviors:",
# "Organisation and Planning: How would you describe his organisation and planning skills? ",
# "Thinking about your interaction with me, I demonstrate the following behaviors:",
# "Alternate people to talk to incase ",
# "Через сколько лет Танечка выберет постоянное место жительства и обзаведется семьей?",
# "How is this interface",
# "Rate me as a team member (5 is the highest)",
# "Rate the candidate on ability to manage his team?",
# "In what context do you know the candidate and since when?",
# "Would you use it for your other businesses? Refer them to friends?",
# "What are the areas in which I should improve?",
# "What is your relationship with Gangadhar Atmakuri?",
# "what is my name",
# "P. F. Superannuation details: Previous P F No",
# "Do u have passport? if yes then please fill",
# "Could you comment on the candidate's general character & behavior?",
# "I hereby nominate the following person for receiving the montly widow pension(available under para 16(2) (a) (i) and (ii) in the event of my death without leaving any eligible family member for receiving pension.",
# "Would you recommend this service to friends and family? if no, why not?",
# "EMP CODE/ ASSOCIATE CO",
# "Ability to work with others",
# "Select the choices that accurately represent vineet jawa",
# "Select the choices that accurately represent Ruchi Sood",
# "Written feedback: greatest strength and one area Keshav Viswanath can improve upon",
# "Does Tanya have any links with the Russian Mafia?",
# "Describe the candidate's general character and behavior",
# "Honesty",
# "How many more times will crazy Tanya come to India?",
# "What do you think about my dressing sense?",
# "Written feedback: greatest strength and one area aakash arora can improve upon",
# "Rate the candidate on a Scale of 1-5 (5 being highest): Verbal communication / Written",
# "Would you be willing to provide a positive recommendation for me if I needed one?",
# "Kya tumhari mummy ne kabhi raat ko sone ke pehle daraya hai kya ki \"Beta soja warna gogo aa jayega!\"",
# "Please give an overall rating for the candidate",
# "Did he have a good understanding of your business needs? Examples? ",
# "How would you rate your overall experience with IDfy on a scale of 1 to 5? (1:lowest, 5:highest)",
# "Thinking about your interaction with Mayank Jain, he/she demonstrates the following behaviors:",
# "What best describes my personality at work?",
# "What best describes Max Cameron's personality at work?",
# "Would you rent to this person again? If no, please explain.",
# "This pops up easily from an UI/UX perspective",
# "Do you have any proceedings pending currently against you that can result in a conviction? If yes, please give details of the offence(s)",
# "You worked with me at?",
# "How did you come to know of our service/website? ",
# "What will Viraj be like 7 years from now?",
# "What are the areas in which the candidate needs to improve?",
# "What can Hatim Baheranwala improve upon?",
# "How do you know the candidate?",
# "How long have you known the candidate",
# "Select the choices that accurately represent mahendran swamy",
# "Select the choices that accurately represent Nikhil Dhok",
# "Since when do you know the candidate and in what context?",
# "What are the candidate’s professional strengths?",
# "How likely are you to recommend working with aakash arora to another colleague?",
# "Has Kaushik ever picked you up from anywhere in the world in his super awesome CAR?",
# "Were there any complaints from the neighbours?",
# "Have you ever used any other background verification service? If yes, how would you rate our service compared to them? ",
# "The candidate will be working with children directly; please share if you think this candidate may be unsuitable to work with children and why (anger management particularly)",
# "How long have you known him/her?",
# "How long have you been using this number?",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Organisation and Planning",
# "Policy No",
# "When was a time you saw me being my best (being in my “element” while making a positive contribution)?",
# "Are there any specific problems you would like to mention?",
# "Number of Full-time founders when startup was founded?",
# "Written feedback: greatest strength and one area that I can improve upon",
# "Date of Verification",
# "Select the choices that accurately represent Gautam N",
# "Professional Strengths",
# "Rate the candidate on - Perseverance and motivation",
# "What is your understanding of his ability with software packages and familiarity with Sandvik equipment / machinery? ",
# "What is your professional relationship with the candidate?",
# "Any additional comments on the candidate?",
# "Suggest any changes to improve Kaushik's chances of GETTING A GIRL?",
# "When did the tenant rent from you?",
# "What can Raghav Kumar improve upon?",
# "What can mahendran swamy improve upon?",
# "BLOOD GROUP",
# "Mayank Jain demonstrates the following behavior:",
# "How does the candidate communicate with his/her peers/juniors?",
# "Select the choices that accurately represent me",
# "kjdfgkasghl",
# "Describe briefly the candidate's relationship with the people he/she worked/works with",
# "DETAILS OF PRESENT ACCOUNT",
# "How likely are you to recommend me to others? (10 is most likely)",
# "What is your overall take on the platform?",
# "Job Skills",
# "Rate me on my ability to adhere to schedules and deadlines (5 is the highest)",
# "Rate the candidate on a Scale of 1-5 (5 being highest): Ability to work with others",
# "How likely are you to recommend working with Irshad Shaikh to another colleague?",
# "What is your relationship with Mayank Jain?",
# "Would you want to be on our mailing list for future updates and information on our activities? If yes, please share with us the email id you would like to be contacted on in the 'any additional comments' box.",
# "What can I improve upon?",
# "What are my professional strengths?",
# "How many years do you think will it take Kaushik to get a girl?",
# "What can Nikhil Dhok improve upon?",
# "How likely are you to recommend working with Max Cameron to another colleague?",
# "DETAILS OF PREVIOUS ACCOUNT (WHICH IS TO BE TRANSFERRED)",
# "Select the choices that accurately represent Max Cameron",
# "Can you confirm the candidate’s job title, dates of employment and work duties?",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Professionalism",
# "What best describes Keshav Viswanath's personality at work?",
# "Was the tenant considerate of neighbours?",
# "Question#3",
# "How long have you worked with me?",
# "What best describes mahendran swamy's personality at work?",
# "Customer Focus",
# "Gangadhar Atmakuri demonstrates the following behavior:",
# "Company or Brand's handles/addresses on Facebook, Twitter, LinkedIn?",
# "Temporary Address",
# "Do you have an IDfy account? If 'yes', please mention your IDfy number in comments.",
# "How did you hear about them?",
# "Did the tenant pay on time?",
# "Name of the Corporate",
# "Could you comment on the candidate's ability to work in a team?",
# "Work Standards:\tHow would you rate the standard of his work?\tWhy? Please provide some examples",
# "Would you rehire this candidate? Please share the reason, if the candidate is not considered for rehire.",
# "Rate the candidate on a scale of 1 to 5 on the following attributes. (1 being the lowest and 5 being the highest): Decision making and initiative",
# "Reliability",
# "How long have you worked with Gangadhar Atmakuri?",
# "How many time was the rent delayed?",
# "In what areas does the candidate need improvement?",
# "What are the candidate's professional strengths?",
# "How likely are you to recommend working with Gautam N to another colleague?",
# "How easy was it to deploy on the platform? What is the Deployment process",
# "What best describes Karin Teodorovicz's personality at work?",
# "Employment Details",
# "Perseverance and motivation",
# "Rate the candidate on a scale of 1 to 5 on: Integrity (1 being the lowest and 5 being the highest)",
# "What best describes Sandeep Warrier's personality at work?",
# "Mobile Number",
# "Weaknesses: What are the areas that he needs to develop?",
# "How likely are you to recommend working with Sandeep Warrier to another colleague?",
# "Attitude towards Work",
# "Have you seen my movie Andaaz Apna Apna?",
# "When do you think Viraj will get married (To a GIRL)?",
# "Marital Status",
# "Would you use Truckky again? Refer them to friends?",
# "Rate us on the following:",
# "What can Gautam N improve upon?",
# "How would you rate the services provided by IDfy? ",
# "Select the choices that accurately represent Raghav Kumar",
# "What best describes Gautam N's personality at work?",
# "What's the wildest thing Viraj has ever done in Goa? You can add your own..",
# "Rate us on your overall experience",
# "Select the choices that accurately represent Sandeep Warrier",
# "Written feedback: greatest strength and one area Nikhil Dhok can improve upon",
# "How many times have you used Truckky?",
# "What best describes Raghav Kumar's personality at work?",
# "Written feedback: greatest strength and one area Max Cameron can improve upon",
# "Has the candidate taken accountability for any mistake he/she has made?",
# "Written feedback: greatest strength and one area mahendran swamy can improve upon",
# "P. F. Superannuation details: Do you intend to continue your existing P F/Superannuation",
# "What is PDS",
# "Written feedback: greatest strength and one area Ruchi Sood can improve upon",
# "What are some of the drawbacks?",
# "Rate the candidate on a Scale of 1-5 (5 being highest): Technical Competence",
# "Rate the candidate on time management",
# "Emp ID No. as appearing in the policy",
# "Communication Skills",
# "Can you describe the benefits of using Truckky service? What is your current commercial agreement with them?",
# "Date of Joining",
# "Initial Place of Posting",
# "Select the choices that accurately represent Karin Teodorovicz",
# "Could you comment on my general character & behavior?",
# "Verbal communication / Written",
# "how r u ",
# "In what condition did you receive the property in, at the end of the Tenancy?",
# "Rate me please",
# "Fathers'/Husband's Name",
# "Do you think this workshop has facilitated/initiated a transformation process in you?",
# "What can Irshad Shaikh improve upon?",
# "What best describes Irshad Shaikh's personality at work?",
# "Any other comments you would like to share",
# "Written feedback: greatest strength and one area vineet jawa can improve upon",
# "How likely are you to recommend working with Ruchi Sood to another colleague?",
# "how r u",
# "How long have you used Trucks? ",
# "What are the areas you think I need to improve?",
# "Trust Name",
# "Other Blog pages and Quora handles (could belong to founder(s) as well)?",
# "feedback for me..",
# "You worked/work with me at?",
# "Select the choices that accurately represent Keshav Viswanath",
# "How likely are you to recommend working with Keshav Viswanath to another colleague?",
# "IFS code of Bank branch",
# "Can you describe the benefits of using Truckky services?"] 

end